### ISSUE TITLE
Editor Hierarchy Window

### ISSUE THREAD

**Issue by PythooonUser** [Interrupt/delverengine#166]
![grafik](https://user-images.githubusercontent.com/13063023/97776103-de4a7300-1b65-11eb-850c-0eb140cdd42d.png)
MK I

## Summary
This issue describes a feature request for an editor hierarchy window commonly found in applications like Unity, Blender etc.
It features a collaspable listing of objects in a scene, highlighting, selecting, drag-and-drop support etc.

In the following different stages of the hierarchy window development are listed, please add any feature requests below.

### MK I (finished)
- [x] Editor hierarchy window
- [x] Entity listing
- [x] Synchronized selection of entities
- [x] Search bar
- [x] Info text regarding searched/found entities in the scene

**PR:** #165 

### MK II
- [ ] Proper editor window
- [ ] Proper tree view
- [ ] Collpasable entries when group, having attached entities
- [ ] Multiple selection support

### MK III
- [ ] Drag-and-drop support to compose/construct grouped/attached entities
- [ ] Distinction between entities (dynamic/non-colliding/static) and markers
- [ ] Incorporation as basic UI element (at the left side of the screen)
- [ ] Conditional rendering/updating of certain parts of the hierarchy (perf)?
- [ ] "Create" menu that displays the right-click menu

**Comment by PythooonUser** [comment]
Closing stale PR as this is not being worked on currently.
